version: '3.8'

services:
  app:
    container_name: aiphoria_audio_converter
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 5000:5000
    networks:
      
      - ropewalk_network
networks:
  ropewalk_network:
    external: true
 
    
