FROM python:3.9-slim

RUN apt-get update && \
    apt-get install -y ffmpeg \
        libavcodec-extra \
        libavformat-dev \
        libavfilter-dev \
        libavdevice-dev \
        libswscale-dev \
        libswresample-dev \
        libpostproc-dev && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip

WORKDIR /app

COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

COPY . /app/

ENV DOCKER_CONTAINER=true \
    FLASK_APP=app.py \
    FLASK_DEBUG=1 \
    PYTHONUNBUFFERED=1

EXPOSE 5000

CMD ["flask", "run", "--host=0.0.0.0", "--port=5000"]
